---
- name: Setup Mysql with accounts db and remote login
  hosts: dbsrvgrp
  gather_facts: false
  tasks:
    - name: Installing Mysql Service and dependencies
      ansible.builtin.package:
        name: "{{item}}"
        state: present
        update_cache: yes
        cache_valid_time: 86400
      loop:
        - mysql-server
        - mysql-client
        - python3-mysqldb
        - libmysqlclient-dev
      ignore_errors: yes
    
    - name: Start and enable mysql Service
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes

    - name: Create database user
      community.mysql.mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        host: '%'
        state: present
    
    - name: Create accounts db
      community.mysql.mysql_db:
        name: "{{dbname}}"
        state: present
    
    - name: Enable remote login to mysql svc
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.conf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      notify:
        - Restart mysql

  handlers:
    - name: Restart mysql
      ansible.builtin.service:
        name: mysql
        state: restarted


      
        