---
- name: Deploy SQL file on accounts db
  hosts: dbsrvgrp
  gather_facts: no
  tasks:
    - name: Import MySql config Variables
      ansible.builtin.include_vars: group_vars/dbsrvgrp
      
    - name: Copy SQL to dbsrvgrp
      ansible.builtin.copy:
        src: files/db_backup.sql
        dest: /tmp/db_backup.sql
  
    - name: Restoring db
      community.mysql.mysql_db:
        name: accounts
        login_user: "{{dbuser}}"
        login_password: "{{dbpass}}"
        state: import
        target: /tmp/db_backup.sql
      notify:
        - Restart mysql

  handlers:
    - name: Restart mysql
      ansible.builtin.service:
        name: mysql
        state: restarted